### ISSUE TITLE
Update styles of release table

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/snapcraft.io#1308]
Designs: https://github.com/canonicalltd/snapcraft-design/issues/552

### TODO:

- [x] improve grid/spacing as per design
- [x] remove borders from contextual menu button
- [x] smaller X cancel release button
- [x] highlight pending releases in 'yellowish'
- [x] fix size of the table when nothing is released yet
- [x] make sure it looks nice for 6 archs (/surl/releases)
