### ISSUE TITLE
Market page improvements

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/snapcraft.io#365]
List of market page improvements to discuss/plan before this page goes live.
From @lyubomir-popov and @Greggless comments on #341

- [x] The screenshots UI is still bit confusing (especially image selection not being visible enough, marking for deletion not being clear) - _**reported in #410**_
- [x] No multiple select and delete for images ( 🎖enhancement)  - _**reported in #411**_
- [x] Uploading a mix of valid and invalid file formats does not upload any of the selection - _**reported in #412**_
- [x] No help text for file format requirements (🎖enhancement) - _**reported in #413**_
- [x] validation for file happens after clicking 'apply' (🎖enhancement) - _**reported in #413**_
- [x] No in-line errors (🎖enhancement) - _**reported in #413**_
- [x] Tab + ◀️ ▶️ key navigation between images (🎖enhancement) - _**reported in #414**_

**Comment by bartaz** [comment]
Previous discussion about designing screenshots states: https://github.com/canonicalltd/snappy-design-squad/issues/356
