### ISSUE TITLE
Reserve name template UX improvements

### ISSUE THREAD

**Issue by Lukewh** [canonical-websites/snapcraft.io#678]
Issue to address feedback from: https://github.com/canonical-websites/snapcraft.io/pull/670

> Relatedly, you can change the “Snap name” value to a name that isn’t taken. If you do that, the rest of the form still assumes that you’re requesting a reserved name, when you no longer are.
>
>A minimal way to fix this would be for the “Request reserved name” form not to contain a “Snap name” field at all. (And since that was the only place the name was disclosed, the intro text would need changing to remind you what name you’re trying to request.)

#### Tasks:
- [x] Remove 'Snap name' field
- [x] Use the `SNAP_NAME` that is being requested in the form title
- [x] Change intro text
- [x] Remove privacy and store selection (user already set this on the previous page)

_It'll be laid out a little like this:_

<hr>

_Title:_
## Request the name '<SNAP_NAME>'

_Intro:_
#### Supporting comment
`textfield`

                                                     `Cancel`          **`[Request name]`**
<hr>

**Comment by Lukewh** [comment]
This work has been done and is now superceded by https://github.com/canonicalltd/snap-squad/issues/536
